### ISSUE TITLE
Yeoman no detection

### ISSUE THREAD

**Issue by Lmendev** [gverschuur/generator-php-cli-app#1]
This generator no works for me. When I run Yo command, Yeoman doesn't recognize it.

**Comment by kostajh** [comment]
Same here.

**Comment by verschuur** [comment]
My apologies, I completely missed this issue. I've been having the same error when using the NPM version, I'll get on it and keep you updated.

**Comment by verschuur** [comment]
Fixed in ab4fe5ca00965be01a679dd74625602d3db5acd0. Please give it a try.

**Comment by verschuur** [comment]
@kostajh, @lmendoza92, could you please update the generator and give it a try, see if the issue is fixed for you?

**Comment by kostajh** [comment]
@gverschuur it works, but I get "Could not open input file" when I try to run the example command.

**Comment by verschuur** [comment]
@kostajh When the generator has finished running and I run 

`php test` I get the response  `Test version 1.0` which is as expected. 

Is the PHP CLI command callable from the command line? And if so, can you give me some info about your setup? OS, PHP version, etc

**Comment by verschuur** [comment]
Closed due to inactivity.
